#!/bin/bash

echo "updating sources.list"
sudo rm /etc/apt/sources.list
sudo cp /home/mark/.installscripts/sources.list /etc/apt/sources.list

echo "Upgrading to unstable"
sudo apt-get update 
sudo apt-get -y dist-upgrade 
sudo apt-get -y autoremove --purge

echo "Installing base packages"
sudo apt-get -y install xorg i3-wm nvidia-driver rxvt-unicode suckless-tools feh compton cups pulseaudio pavucontrol pulseaudio-module-bluetooth bluez unzip flatpak

sudo apt-get -y autoremove --purge
sudo apt-get -y autoclean

echo "Adding flathub repo"
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

echo "Changing Caps Lock to Super"
sudo rm /usr/share/X11/xkb/symbols/pc
sudo cp /home/mark/.installscripts/pc /usr/share/X11/xkb/symbols/pc

echo "Fixing boot with nvidia driver"
sudo rm /etc/default/grub
sudo cp /home/mark/.installscripts/grub /etc/default/grub
sudo update-grub

echo "installing xpadneo"
git clone https://github.com/atar-axis/xpadneo.git
cd xpadneo
sudo ./install.sh
cd ..

echo "updating bluetooth config"
sudo rm /etc/bluetooth/input.conf
sudo cp /home/mark/.installscripts/input.conf /etc/bluetooth/input.conf

echo "Mounting data drive"
mkdir /home/mark/data
echo "UUID=996a7f1a-8791-4f04-9139-b700cf9b691f /home/mark/data ext4 defaults 0 1" | sudo tee -a /etc/fstab

echo "Setting up auto login"
sudo mkdir /etc/systemd/system/getty@tty1.service.d/
cat /home/mark/.installscripts/login | sudo tee /etc/systemd/system/getty@tty1.service.d/override.conf
systemctl enable getty@tty1.service

chmod +x /home/mark/.rootscripts/*

echo "Please restart computer"
