#!/bin/bash

echo "updating sources.list"
sudo rm /etc/apt/sources.list
sudo cp $HOME/.installscripts/sources.list /etc/apt/sources.list

echo "adding vscode repo"
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" |sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
rm -f packages.microsoft.gpg
sudo apt install -y apt-transport-https

echo "Upgrading to unstable"
sudo apt update 
sudo apt -y dist-upgrade 
sudo apt -y autoremove --purge

echo "Installing base packages"
sudo apt -y install xorg i3-wm nvidia-driver rxvt-unicode rofi feh compton cups pulseaudio pavucontrol pulseaudio-module-bluetooth bluez unzip flatpak steam-devices code

sudo apt -y autoremove --purge
sudo apt -y autoclean

echo "Adding flathub repo"
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

echo "Installing flatpaks"
flatpak install -y flathub com.valvesoftware.Steam
flatpak install -y flathub org.mozilla.firefox
flatpak install -y flathub com.github.tchx84.Flatseal

echo "Changing Caps Lock to Super"
sudo rm /usr/share/X11/xkb/symbols/pc
sudo cp $HOME/.installscripts/pc /usr/share/X11/xkb/symbols/pc

echo "Fixing boot with nvidia driver"
sudo rm /etc/default/grub
sudo cp $HOME/.installscripts/grub /etc/default/grub
sudo update-grub

echo "installing xpadneo"
git clone https://github.com/atar-axis/xpadneo.git $HOME/.installscripts/xpadneo
sudo $HOME/.installscripts/xpadneo/install.sh

echo "updating bluetooth config"
sudo rm /etc/bluetooth/input.conf
sudo cp $HOME/.installscripts/input.conf /etc/bluetooth/input.conf

echo "Mounting data drive"
mkdir $HOME/data
echo "UUID=996a7f1a-8791-4f04-9139-b700cf9b691f $HOME/data ext4 defaults 0 1" | sudo tee -a /etc/fstab

echo "Setting up auto login"
sudo mkdir /etc/systemd/system/getty@tty1.service.d/
cat $HOME/.installscripts/login | sudo tee /etc/systemd/system/getty@tty1.service.d/override.conf
systemctl enable getty@tty1.service

chmod +x $HOME/.rootscripts/*

echo "Update sudoers"
cat $HOME/.installscripts/visudo_append | sudo EDITOR='tee -a' visudo

echo "Please restart computer"
